# git 올릴때 빼고 올릴것
server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://project1.cxg8vdlfu0la.ap-southeast-2.rds.amazonaws.com:3306/gogo
    username: admin
    password: '00000000'
  #    url: jdbc:mysql://localhost:3306/project02
  #    username: root
  #    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # DDL?? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true # 예약어 컬럼 사용

cloud:
  aws:
    s3:
      bucket: gogo-img
    credentials:
      access-key: AKIAXI3RTB4GYX6ONJ5P
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false